services:
  - type: web
    name: portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
    autoDeploy: true